/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ttthread.ihm;

import ttthread.ctrl.Ctrl;

/**
 *
 * @author Waebela
 */
public class Ihm extends javax.swing.JFrame {

    /**
     * Creates new form Ihm
     */
    public Ihm() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelChrono = new javax.swing.JPanel();
        lChrono = new javax.swing.JLabel();
        bStart = new javax.swing.JButton();
        bPause = new javax.swing.JButton();
        bStop = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        pbActivity = new javax.swing.JProgressBar();
        panelGestionThread = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taComment = new javax.swing.JTextArea();
        bDemarreThread = new javax.swing.JButton();
        bArreteThread1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TestTechno Thread");

        panelChrono.setBackground(new java.awt.Color(255, 255, 204));

        lChrono.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lChrono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lChrono.setText("00:00.000");
        lChrono.setToolTipText("");

        bStart.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bStart.setText("Start");
        bStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStartActionPerformed(evt);
            }
        });

        bPause.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bPause.setText("Pause");
        bPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPauseActionPerformed(evt);
            }
        });

        bStop.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bStop.setText("Stop");
        bStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStopActionPerformed(evt);
            }
        });

        bReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bReset.setText("Reset");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });

        pbActivity.setBackground(new java.awt.Color(153, 255, 255));

        javax.swing.GroupLayout panelChronoLayout = new javax.swing.GroupLayout(panelChrono);
        panelChrono.setLayout(panelChronoLayout);
        panelChronoLayout.setHorizontalGroup(
            panelChronoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChronoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelChronoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lChrono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelChronoLayout.createSequentialGroup()
                        .addGroup(panelChronoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pbActivity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelChronoLayout.createSequentialGroup()
                                .addComponent(bStart, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bPause, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bStop, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bReset, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        panelChronoLayout.setVerticalGroup(
            panelChronoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChronoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lChrono, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelChronoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bStart)
                    .addComponent(bPause)
                    .addComponent(bStop)
                    .addComponent(bReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbActivity, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelGestionThread.setBackground(new java.awt.Color(102, 255, 102));

        taComment.setEditable(false);
        taComment.setBackground(new java.awt.Color(204, 255, 204));
        taComment.setColumns(20);
        taComment.setRows(5);
        jScrollPane1.setViewportView(taComment);

        bDemarreThread.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bDemarreThread.setText("Demarre Thread");
        bDemarreThread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDemarreThreadActionPerformed(evt);
            }
        });

        bArreteThread1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bArreteThread1.setText("Arrête Thread");
        bArreteThread1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bArreteThread1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGestionThreadLayout = new javax.swing.GroupLayout(panelGestionThread);
        panelGestionThread.setLayout(panelGestionThreadLayout);
        panelGestionThreadLayout.setHorizontalGroup(
            panelGestionThreadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(panelGestionThreadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bDemarreThread, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bArreteThread1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelGestionThreadLayout.setVerticalGroup(
            panelGestionThreadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGestionThreadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGestionThreadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bDemarreThread)
                    .addComponent(bArreteThread1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelChrono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelGestionThread, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelChrono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGestionThread, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStartActionPerformed
        refCtrl.startChrono();
    }//GEN-LAST:event_bStartActionPerformed

    private void bPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPauseActionPerformed
        refCtrl.pauseChrono();
    }//GEN-LAST:event_bPauseActionPerformed

    private void bStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStopActionPerformed
        refCtrl.stopChrono();
    }//GEN-LAST:event_bStopActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        refCtrl.resetChrono();
    }//GEN-LAST:event_bResetActionPerformed

    private void bDemarreThreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDemarreThreadActionPerformed
        refCtrl.demarreThread();
    }//GEN-LAST:event_bDemarreThreadActionPerformed

    private void bArreteThread1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bArreteThread1ActionPerformed
        refCtrl.arreteThread();
    }//GEN-LAST:event_bArreteThread1ActionPerformed

    public void afficheChrono(String temps) {
        lChrono.setText(temps);
    }

    public void afficheActivity(int valeur, String texte) {
        pbActivity.setValue(valeur);
//        pbActivity.setStringPainted(true);
        pbActivity.setString(texte);
        pbActivity.setStringPainted(true);
    }

    public void afficheMsg(String msg) {
        taComment.append(msg + "\n");
    }

    public void afficheErr(String err) {
        taComment.append("ERROR - " + err + "\n");
    }

    public void setRefCtrl(Ctrl refCtrl) {
        this.refCtrl = refCtrl;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bArreteThread1;
    private javax.swing.JButton bDemarreThread;
    private javax.swing.JButton bPause;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bStart;
    private javax.swing.JButton bStop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lChrono;
    private javax.swing.JPanel panelChrono;
    private javax.swing.JPanel panelGestionThread;
    private javax.swing.JProgressBar pbActivity;
    private javax.swing.JTextArea taComment;
    // End of variables declaration//GEN-END:variables
    private Ctrl refCtrl;
}
